datasource:
  mysql:
    url: jdbc:mysql://192.168.2.130:3306/qiming_test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowMultiQueries=true&useSSL=true&verifyServerCertificate=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 10
    maxWait: 60000
    minIdle: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: "select 1"
    testWhileIdle: true
    maxOpenPreparedStatements: 20
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    useGlobalDataSourceStat: true

    logging.config: classpath:logback-spring.xml

server:
  port: 8080